# !!!
# Create http-client.private.env.json and init variables
# !!!

### Get OAuth Access Token
# !!! replace "code" query param
# !!! you can use PAT Github token as well: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
# !!! For code navigate to:
# https://github.com/login/oauth/authorize?client_id=Iv1.94657f4b86f3738d&redirect_uri=http://localhost:8080/oauth/access_token
POST localhost:8080/oauth/access_token?code=XXX
Accept: application/json

> {% client.global.set("token", response.body.access_token); %}

### Current logged user
GET {{hostname}}/user
Accept: application/json
Authorization: Bearer {{gh-token}}

### Get List of all Sa10 instalations for the {{organization}}
GET {{hostname}}/user/{{organization}}
Content-Type: application/json
Authorization: Bearer {{gh-token}}

### Get the {{name}} Sa10 instalations from the {{organization}}
GET {{hostname}}/salo/{{organization}}/{{name}}
Content-Type: application/json
Authorization: Bearer {{gh-token}}

### Get the {{name}} Sa10 installations status from the {{organization}}
GET {{hostname}}/salo/{{organization}}/{{name}}/status
Content-Type: application/json
Authorization: Bearer {{gh-token}}

### Get List of Sa10 templates
GET {{hostname}}/salo/{{organization}}/templates
Content-Type: application/json
Authorization: Bearer {{gh-token}}

### Create a new Sa10 instalation in the {{organization}}
POST {{hostname}}/salo/{{organization}}
Content-Type: application/json
Authorization: Bearer {{gh-token}}

{
  "name": "{{name}}",
  "cloudProvider": "AWS",
  "organization": "{{organization}}",
  "ingressConfig": {
    "domain": "sdlcvitech.com",
    "tls": {
      "email": "{{email}}"
    }
  },
  "environments": [
    {
      "cluster": {
        "name": "{{name}}-cluster",
        "jxBotUsername": "{{gh-username}}",
        "cloudProviderClientId": "{{aws-client-id}}",
        "cloudProviderSecret": "{{aws-secret}}",
        "domainOwner": true,
        "region": "us-east-2",
        "nodeGroups": [
          {
            "name": "pipelines",
            "maxSize": 2,
            "minSize": 1,
            "spotSize": 1,
            "labels": [],
            "taints": [],
            "tags": [],
            "volumeSize": 60,
            "vmTypes": [
              "m5.xlarge"
            ]
          },
          {
            "name": "main",
            "maxSize": 2,
            "minSize": 1,
            "spotSize": 1,
            "labels": [],
            "taints": [],
            "tags": [],
            "volumeSize": 60,
            "vmTypes": [
              "m5.xlarge"
            ]
          }
        ]
      },
      "config": {
        "key": "dev",
        "promotionStrategy": "Auto"
      }
    }
  ]
}

### Deploy Sa10 installation
POST {{hostname}}/salo/{{organization}}/{{name}}/apply
Content-Type: application/json
Authorization: Bearer {{gh-token}}

### Destroy Sa10 installation
POST {{hostname}}/salo/{{organization}}/{{name}}/destroy
Content-Type: application/json
Authorization: Bearer {{gh-token}}
